#!/bin/bash -ex

apt-get -y update
apt-get -y dist-upgrade
apt-get -y install jellyfin

# Rename the file server for WebDAVCGI
CONF=/var/www/webdavcgi/webdav.conf
sed -i "s|FILESERVER|MEDIASERVER|" $CONF

# Rename the samba service
CONF=/etc/samba/smb.conf
sed -i "s|FILESERVER|MEDIASERVER|" $CONF
sed -i "s|FileServer|MediaServer|" $CONF

# Change default group to users
usermod -g users jellyfin

# Setup default media directories
for fn in Music Movies TVShows Photos; do
    mkdir -p /srv/storage/$fn
    chown jellyfin:users /srv/storage/$fn
    chmod g+w /srv/storage/$fn
done

# Apache config for WebDavCGI
a2dissite 000-default.conf
a2ensite webdavcgi.conf
a2ensite tkl-webcp.conf

# Apache config for reverse proxy
echo 'Listen 12322' >> /etc/apache2/ports.conf
a2ensite jellyfin-proxy.conf
a2enmod headers
a2enmod proxy_http
a2enmod proxy_wstunnel

# Fix for broken init.d script, download latest from upstream.
# (note this should be unnecessary for releases AFTER 10.2.2)
wget https://github.com/jellyfin/jellyfin/raw/0e787f4e9fb9f4a7159ca75bcd319c7f908df9a3/deployment/debian-package-x64/pkg-src/jellyfin.init -O /etc/init.d/jellyfin
chmod +x /etc/init.d/jellyfin

service jellyfin start
service apache2 start

until curl -sSf http://localhost:8096 > /dev/null
do
    sleep 1
done
sleep 5

# Perform initial setup
python /usr/local/src/jellyfin-setup.py
service jellyfin stop
service apache2 stop
